name: Testing
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Job:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.0

      - name: Installing Libs
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          sudo apt-get install glibc-source
          sudo apt-get install libidn12
          sudo apt-get install libidn-dev

      - name: Installing Haxe Libraries
        run: |
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec.git

      - name: Building
        run: cd sample && haxelib run lime build linux -debug
